/**
 * @author generated by eTrice
 *
 * Header File of DataClass DataClass1
 * 
 */

#ifndef _DATACLASS1_H_
#define _DATACLASS1_H_

#include "etDatatypes.h"

#include "DataClass2.h"

/*--------------------- begin user code ---------------------*/
	// usercode1
/*--------------------- end user code ---------------------*/
		
typedef struct {
	/*--------------------- attributes ---------------------*/
	int32 Attr1;
	DataClass2 ComplexAttr;
	float32 Attr3;
} DataClass1;


/*--------------------- operations ---------------------*/
int32 DataClass1_MultiplyWithAttr1(DataClass1* self, int32 value);
float32 DataClass1_MultiplyWithAttr3(DataClass1* self, float32 value);

/* deep copy */
void DataClass1_deepCopy(DataClass1* source, DataClass1* target);

/*--------------------- begin user code ---------------------*/
	// usercode2
/*--------------------- end user code ---------------------*/

#endif /* _DATACLASS1_H_ */

