/*
* generated by Xtext
*/
package org.eclipse.etrice.core.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.eclipse.etrice.core.services.RoomGrammarAccess;

public class RoomParser extends AbstractContentAssistParser {
	
	@Inject
	private RoomGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.eclipse.etrice.core.ui.contentassist.antlr.internal.InternalRoomParser createParser() {
		org.eclipse.etrice.core.ui.contentassist.antlr.internal.InternalRoomParser result = new org.eclipse.etrice.core.ui.contentassist.antlr.internal.InternalRoomParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getRoomModelAccess().getAlternatives_5(), "rule__RoomModel__Alternatives_5");
					put(grammarAccess.getRoomClassAccess().getAlternatives(), "rule__RoomClass__Alternatives");
					put(grammarAccess.getStructureClassAccess().getAlternatives(), "rule__StructureClass__Alternatives");
					put(grammarAccess.getActorContainerClassAccess().getAlternatives(), "rule__ActorContainerClass__Alternatives");
					put(grammarAccess.getDataTypeAccess().getAlternatives(), "rule__DataType__Alternatives");
					put(grammarAccess.getComplexTypeAccess().getAlternatives(), "rule__ComplexType__Alternatives");
					put(grammarAccess.getOperationAccess().getAlternatives(), "rule__Operation__Alternatives");
					put(grammarAccess.getStandardOperationAccess().getAlternatives_5_1(), "rule__StandardOperation__Alternatives_5_1");
					put(grammarAccess.getPortOperationAccess().getAlternatives_5(), "rule__PortOperation__Alternatives_5");
					put(grammarAccess.getPortOperationAccess().getAlternatives_5_0_1(), "rule__PortOperation__Alternatives_5_0_1");
					put(grammarAccess.getPortClassAccess().getAlternatives_2(), "rule__PortClass__Alternatives_2");
					put(grammarAccess.getSemanticsRuleAccess().getAlternatives_1_1(), "rule__SemanticsRule__Alternatives_1_1");
					put(grammarAccess.getActorClassAccess().getAlternatives_7_6(), "rule__ActorClass__Alternatives_7_6");
					put(grammarAccess.getInterfaceItemAccess().getAlternatives(), "rule__InterfaceItem__Alternatives");
					put(grammarAccess.getActorContainerRefAccess().getAlternatives(), "rule__ActorContainerRef__Alternatives");
					put(grammarAccess.getSAPointAccess().getAlternatives(), "rule__SAPoint__Alternatives");
					put(grammarAccess.getStateGraphNodeAccess().getAlternatives(), "rule__StateGraphNode__Alternatives");
					put(grammarAccess.getStateGraphItemAccess().getAlternatives(), "rule__StateGraphItem__Alternatives");
					put(grammarAccess.getStateAccess().getAlternatives(), "rule__State__Alternatives");
					put(grammarAccess.getStateGraphAccess().getAlternatives(), "rule__StateGraph__Alternatives");
					put(grammarAccess.getPlainStateGraphAccess().getAlternatives_2(), "rule__PlainStateGraph__Alternatives_2");
					put(grammarAccess.getStateMachineAccess().getAlternatives_4(), "rule__StateMachine__Alternatives_4");
					put(grammarAccess.getTrPointAccess().getAlternatives(), "rule__TrPoint__Alternatives");
					put(grammarAccess.getTransitionAccess().getAlternatives(), "rule__Transition__Alternatives");
					put(grammarAccess.getNonInitialTransitionAccess().getAlternatives(), "rule__NonInitialTransition__Alternatives");
					put(grammarAccess.getTransitionTerminalAccess().getAlternatives(), "rule__TransitionTerminal__Alternatives");
					put(grammarAccess.getImportAccess().getAlternatives_1(), "rule__Import__Alternatives_1");
					put(grammarAccess.getRoomModelAccess().getGroup(), "rule__RoomModel__Group__0");
					put(grammarAccess.getVarDeclAccess().getGroup(), "rule__VarDecl__Group__0");
					put(grammarAccess.getRefableTypeAccess().getGroup(), "rule__RefableType__Group__0");
					put(grammarAccess.getPrimitiveTypeAccess().getGroup(), "rule__PrimitiveType__Group__0");
					put(grammarAccess.getPrimitiveTypeAccess().getGroup_4(), "rule__PrimitiveType__Group_4__0");
					put(grammarAccess.getExternalTypeAccess().getGroup(), "rule__ExternalType__Group__0");
					put(grammarAccess.getDataClassAccess().getGroup(), "rule__DataClass__Group__0");
					put(grammarAccess.getDataClassAccess().getGroup_3(), "rule__DataClass__Group_3__0");
					put(grammarAccess.getDataClassAccess().getGroup_5(), "rule__DataClass__Group_5__0");
					put(grammarAccess.getDataClassAccess().getGroup_6(), "rule__DataClass__Group_6__0");
					put(grammarAccess.getDataClassAccess().getGroup_7(), "rule__DataClass__Group_7__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup_5(), "rule__Attribute__Group_5__0");
					put(grammarAccess.getStandardOperationAccess().getGroup(), "rule__StandardOperation__Group__0");
					put(grammarAccess.getStandardOperationAccess().getGroup_3(), "rule__StandardOperation__Group_3__0");
					put(grammarAccess.getStandardOperationAccess().getGroup_3_1(), "rule__StandardOperation__Group_3_1__0");
					put(grammarAccess.getStandardOperationAccess().getGroup_5(), "rule__StandardOperation__Group_5__0");
					put(grammarAccess.getPortOperationAccess().getGroup(), "rule__PortOperation__Group__0");
					put(grammarAccess.getPortOperationAccess().getGroup_3(), "rule__PortOperation__Group_3__0");
					put(grammarAccess.getPortOperationAccess().getGroup_3_1(), "rule__PortOperation__Group_3_1__0");
					put(grammarAccess.getPortOperationAccess().getGroup_5_0(), "rule__PortOperation__Group_5_0__0");
					put(grammarAccess.getPortOperationAccess().getGroup_5_1(), "rule__PortOperation__Group_5_1__0");
					put(grammarAccess.getProtocolClassAccess().getGroup(), "rule__ProtocolClass__Group__0");
					put(grammarAccess.getProtocolClassAccess().getGroup_3(), "rule__ProtocolClass__Group_3__0");
					put(grammarAccess.getProtocolClassAccess().getGroup_5(), "rule__ProtocolClass__Group_5__0");
					put(grammarAccess.getProtocolClassAccess().getGroup_6(), "rule__ProtocolClass__Group_6__0");
					put(grammarAccess.getProtocolClassAccess().getGroup_7(), "rule__ProtocolClass__Group_7__0");
					put(grammarAccess.getProtocolClassAccess().getGroup_8(), "rule__ProtocolClass__Group_8__0");
					put(grammarAccess.getProtocolClassAccess().getGroup_9(), "rule__ProtocolClass__Group_9__0");
					put(grammarAccess.getProtocolClassAccess().getGroup_10(), "rule__ProtocolClass__Group_10__0");
					put(grammarAccess.getProtocolClassAccess().getGroup_11(), "rule__ProtocolClass__Group_11__0");
					put(grammarAccess.getMessageAccess().getGroup(), "rule__Message__Group__0");
					put(grammarAccess.getPortClassAccess().getGroup(), "rule__PortClass__Group__0");
					put(grammarAccess.getPortClassAccess().getGroup_1(), "rule__PortClass__Group_1__0");
					put(grammarAccess.getMessageHandlerAccess().getGroup(), "rule__MessageHandler__Group__0");
					put(grammarAccess.getProtocolSemanticsAccess().getGroup(), "rule__ProtocolSemantics__Group__0");
					put(grammarAccess.getSemanticsRuleAccess().getGroup(), "rule__SemanticsRule__Group__0");
					put(grammarAccess.getSemanticsRuleAccess().getGroup_1(), "rule__SemanticsRule__Group_1__0");
					put(grammarAccess.getSemanticsRuleAccess().getGroup_1_1_1(), "rule__SemanticsRule__Group_1_1_1__0");
					put(grammarAccess.getSemanticsRuleAccess().getGroup_1_1_1_2(), "rule__SemanticsRule__Group_1_1_1_2__0");
					put(grammarAccess.getActorClassAccess().getGroup(), "rule__ActorClass__Group__0");
					put(grammarAccess.getActorClassAccess().getGroup_4(), "rule__ActorClass__Group_4__0");
					put(grammarAccess.getActorClassAccess().getGroup_6(), "rule__ActorClass__Group_6__0");
					put(grammarAccess.getActorClassAccess().getGroup_7(), "rule__ActorClass__Group_7__0");
					put(grammarAccess.getActorClassAccess().getGroup_7_3(), "rule__ActorClass__Group_7_3__0");
					put(grammarAccess.getActorClassAccess().getGroup_7_4(), "rule__ActorClass__Group_7_4__0");
					put(grammarAccess.getActorClassAccess().getGroup_7_5(), "rule__ActorClass__Group_7_5__0");
					put(grammarAccess.getActorClassAccess().getGroup_8(), "rule__ActorClass__Group_8__0");
					put(grammarAccess.getPortAccess().getGroup(), "rule__Port__Group__0");
					put(grammarAccess.getExternalPortAccess().getGroup(), "rule__ExternalPort__Group__0");
					put(grammarAccess.getSAPRefAccess().getGroup(), "rule__SAPRef__Group__0");
					put(grammarAccess.getSPPRefAccess().getGroup(), "rule__SPPRef__Group__0");
					put(grammarAccess.getServiceImplementationAccess().getGroup(), "rule__ServiceImplementation__Group__0");
					put(grammarAccess.getLogicalSystemAccess().getGroup(), "rule__LogicalSystem__Group__0");
					put(grammarAccess.getSubSystemRefAccess().getGroup(), "rule__SubSystemRef__Group__0");
					put(grammarAccess.getSubSystemClassAccess().getGroup(), "rule__SubSystemClass__Group__0");
					put(grammarAccess.getSubSystemClassAccess().getGroup_4(), "rule__SubSystemClass__Group_4__0");
					put(grammarAccess.getSubSystemClassAccess().getGroup_5(), "rule__SubSystemClass__Group_5__0");
					put(grammarAccess.getSubSystemClassAccess().getGroup_6(), "rule__SubSystemClass__Group_6__0");
					put(grammarAccess.getLogicalThreadAccess().getGroup(), "rule__LogicalThread__Group__0");
					put(grammarAccess.getLogicalThreadAccess().getGroup_7(), "rule__LogicalThread__Group_7__0");
					put(grammarAccess.getActorInstancePathAccess().getGroup(), "rule__ActorInstancePath__Group__0");
					put(grammarAccess.getActorInstancePathAccess().getGroup_1(), "rule__ActorInstancePath__Group_1__0");
					put(grammarAccess.getBindingAccess().getGroup(), "rule__Binding__Group__0");
					put(grammarAccess.getBindingEndPointAccess().getGroup(), "rule__BindingEndPoint__Group__0");
					put(grammarAccess.getBindingEndPointAccess().getGroup_0(), "rule__BindingEndPoint__Group_0__0");
					put(grammarAccess.getLayerConnectionAccess().getGroup(), "rule__LayerConnection__Group__0");
					put(grammarAccess.getRefSAPointAccess().getGroup(), "rule__RefSAPoint__Group__0");
					put(grammarAccess.getRelaySAPointAccess().getGroup(), "rule__RelaySAPoint__Group__0");
					put(grammarAccess.getSPPointAccess().getGroup(), "rule__SPPoint__Group__0");
					put(grammarAccess.getActorRefAccess().getGroup(), "rule__ActorRef__Group__0");
					put(grammarAccess.getPlainStateGraphAccess().getGroup(), "rule__PlainStateGraph__Group__0");
					put(grammarAccess.getStateMachineAccess().getGroup(), "rule__StateMachine__Group__0");
					put(grammarAccess.getBaseStateAccess().getGroup(), "rule__BaseState__Group__0");
					put(grammarAccess.getBaseStateAccess().getGroup_3(), "rule__BaseState__Group_3__0");
					put(grammarAccess.getBaseStateAccess().getGroup_3_1(), "rule__BaseState__Group_3_1__0");
					put(grammarAccess.getBaseStateAccess().getGroup_3_2(), "rule__BaseState__Group_3_2__0");
					put(grammarAccess.getBaseStateAccess().getGroup_3_3(), "rule__BaseState__Group_3_3__0");
					put(grammarAccess.getBaseStateAccess().getGroup_3_4(), "rule__BaseState__Group_3_4__0");
					put(grammarAccess.getRefinedStateAccess().getGroup(), "rule__RefinedState__Group__0");
					put(grammarAccess.getRefinedStateAccess().getGroup_4(), "rule__RefinedState__Group_4__0");
					put(grammarAccess.getRefinedStateAccess().getGroup_5(), "rule__RefinedState__Group_5__0");
					put(grammarAccess.getRefinedStateAccess().getGroup_6(), "rule__RefinedState__Group_6__0");
					put(grammarAccess.getRefinedStateAccess().getGroup_7(), "rule__RefinedState__Group_7__0");
					put(grammarAccess.getDetailCodeAccess().getGroup(), "rule__DetailCode__Group__0");
					put(grammarAccess.getTransitionPointAccess().getGroup(), "rule__TransitionPoint__Group__0");
					put(grammarAccess.getEntryPointAccess().getGroup(), "rule__EntryPoint__Group__0");
					put(grammarAccess.getExitPointAccess().getGroup(), "rule__ExitPoint__Group__0");
					put(grammarAccess.getChoicePointAccess().getGroup(), "rule__ChoicePoint__Group__0");
					put(grammarAccess.getInitialTransitionAccess().getGroup(), "rule__InitialTransition__Group__0");
					put(grammarAccess.getInitialTransitionAccess().getGroup_8(), "rule__InitialTransition__Group_8__0");
					put(grammarAccess.getContinuationTransitionAccess().getGroup(), "rule__ContinuationTransition__Group__0");
					put(grammarAccess.getContinuationTransitionAccess().getGroup_7(), "rule__ContinuationTransition__Group_7__0");
					put(grammarAccess.getContinuationTransitionAccess().getGroup_7_1(), "rule__ContinuationTransition__Group_7_1__0");
					put(grammarAccess.getTriggeredTransitionAccess().getGroup(), "rule__TriggeredTransition__Group__0");
					put(grammarAccess.getTriggeredTransitionAccess().getGroup_11(), "rule__TriggeredTransition__Group_11__0");
					put(grammarAccess.getTriggeredTransitionAccess().getGroup_13(), "rule__TriggeredTransition__Group_13__0");
					put(grammarAccess.getGuardedTransitionAccess().getGroup(), "rule__GuardedTransition__Group__0");
					put(grammarAccess.getGuardedTransitionAccess().getGroup_10(), "rule__GuardedTransition__Group_10__0");
					put(grammarAccess.getCPBranchTransitionAccess().getGroup(), "rule__CPBranchTransition__Group__0");
					put(grammarAccess.getCPBranchTransitionAccess().getGroup_10(), "rule__CPBranchTransition__Group_10__0");
					put(grammarAccess.getTrPointTerminalAccess().getGroup(), "rule__TrPointTerminal__Group__0");
					put(grammarAccess.getSubStateTrPointTerminalAccess().getGroup(), "rule__SubStateTrPointTerminal__Group__0");
					put(grammarAccess.getChoicepointTerminalAccess().getGroup(), "rule__ChoicepointTerminal__Group__0");
					put(grammarAccess.getTriggerAccess().getGroup(), "rule__Trigger__Group__0");
					put(grammarAccess.getTriggerAccess().getGroup_2(), "rule__Trigger__Group_2__0");
					put(grammarAccess.getMessageFromIfAccess().getGroup(), "rule__MessageFromIf__Group__0");
					put(grammarAccess.getGuardAccess().getGroup(), "rule__Guard__Group__0");
					put(grammarAccess.getDocumentationAccess().getGroup(), "rule__Documentation__Group__0");
					put(grammarAccess.getAnnotationAccess().getGroup(), "rule__Annotation__Group__0");
					put(grammarAccess.getAnnotationAccess().getGroup_2(), "rule__Annotation__Group_2__0");
					put(grammarAccess.getAnnotationAccess().getGroup_2_2(), "rule__Annotation__Group_2_2__0");
					put(grammarAccess.getKeyValueAccess().getGroup(), "rule__KeyValue__Group__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getImportAccess().getGroup_1_0(), "rule__Import__Group_1_0__0");
					put(grammarAccess.getImportedFQNAccess().getGroup(), "rule__ImportedFQN__Group__0");
					put(grammarAccess.getImportedFQNAccess().getGroup_1(), "rule__ImportedFQN__Group_1__0");
					put(grammarAccess.getFQNAccess().getGroup(), "rule__FQN__Group__0");
					put(grammarAccess.getFQNAccess().getGroup_1(), "rule__FQN__Group_1__0");
					put(grammarAccess.getRoomModelAccess().getNameAssignment_1(), "rule__RoomModel__NameAssignment_1");
					put(grammarAccess.getRoomModelAccess().getDocuAssignment_2(), "rule__RoomModel__DocuAssignment_2");
					put(grammarAccess.getRoomModelAccess().getImportsAssignment_4(), "rule__RoomModel__ImportsAssignment_4");
					put(grammarAccess.getRoomModelAccess().getPrimitiveTypesAssignment_5_0(), "rule__RoomModel__PrimitiveTypesAssignment_5_0");
					put(grammarAccess.getRoomModelAccess().getExternalTypesAssignment_5_1(), "rule__RoomModel__ExternalTypesAssignment_5_1");
					put(grammarAccess.getRoomModelAccess().getDataClassesAssignment_5_2(), "rule__RoomModel__DataClassesAssignment_5_2");
					put(grammarAccess.getRoomModelAccess().getProtocolClassesAssignment_5_3(), "rule__RoomModel__ProtocolClassesAssignment_5_3");
					put(grammarAccess.getRoomModelAccess().getActorClassesAssignment_5_4(), "rule__RoomModel__ActorClassesAssignment_5_4");
					put(grammarAccess.getRoomModelAccess().getSubSystemClassesAssignment_5_5(), "rule__RoomModel__SubSystemClassesAssignment_5_5");
					put(grammarAccess.getRoomModelAccess().getSystemsAssignment_5_6(), "rule__RoomModel__SystemsAssignment_5_6");
					put(grammarAccess.getVarDeclAccess().getNameAssignment_0(), "rule__VarDecl__NameAssignment_0");
					put(grammarAccess.getVarDeclAccess().getRefTypeAssignment_2(), "rule__VarDecl__RefTypeAssignment_2");
					put(grammarAccess.getRefableTypeAccess().getTypeAssignment_0(), "rule__RefableType__TypeAssignment_0");
					put(grammarAccess.getRefableTypeAccess().getRefAssignment_1(), "rule__RefableType__RefAssignment_1");
					put(grammarAccess.getPrimitiveTypeAccess().getNameAssignment_1(), "rule__PrimitiveType__NameAssignment_1");
					put(grammarAccess.getPrimitiveTypeAccess().getTargetNameAssignment_3(), "rule__PrimitiveType__TargetNameAssignment_3");
					put(grammarAccess.getPrimitiveTypeAccess().getCastNameAssignment_4_1(), "rule__PrimitiveType__CastNameAssignment_4_1");
					put(grammarAccess.getPrimitiveTypeAccess().getDefaultValueLiteralAssignment_6(), "rule__PrimitiveType__DefaultValueLiteralAssignment_6");
					put(grammarAccess.getPrimitiveTypeAccess().getDocuAssignment_7(), "rule__PrimitiveType__DocuAssignment_7");
					put(grammarAccess.getExternalTypeAccess().getNameAssignment_1(), "rule__ExternalType__NameAssignment_1");
					put(grammarAccess.getExternalTypeAccess().getTargetNameAssignment_3(), "rule__ExternalType__TargetNameAssignment_3");
					put(grammarAccess.getExternalTypeAccess().getDocuAssignment_4(), "rule__ExternalType__DocuAssignment_4");
					put(grammarAccess.getDataClassAccess().getNameAssignment_1(), "rule__DataClass__NameAssignment_1");
					put(grammarAccess.getDataClassAccess().getDocuAssignment_2(), "rule__DataClass__DocuAssignment_2");
					put(grammarAccess.getDataClassAccess().getBaseAssignment_3_1(), "rule__DataClass__BaseAssignment_3_1");
					put(grammarAccess.getDataClassAccess().getUserCode1Assignment_5_1(), "rule__DataClass__UserCode1Assignment_5_1");
					put(grammarAccess.getDataClassAccess().getUserCode2Assignment_6_1(), "rule__DataClass__UserCode2Assignment_6_1");
					put(grammarAccess.getDataClassAccess().getUserCode3Assignment_7_1(), "rule__DataClass__UserCode3Assignment_7_1");
					put(grammarAccess.getDataClassAccess().getAttributesAssignment_8(), "rule__DataClass__AttributesAssignment_8");
					put(grammarAccess.getDataClassAccess().getOperationsAssignment_9(), "rule__DataClass__OperationsAssignment_9");
					put(grammarAccess.getAttributeAccess().getNameAssignment_1(), "rule__Attribute__NameAssignment_1");
					put(grammarAccess.getAttributeAccess().getSizeAssignment_2(), "rule__Attribute__SizeAssignment_2");
					put(grammarAccess.getAttributeAccess().getRefTypeAssignment_4(), "rule__Attribute__RefTypeAssignment_4");
					put(grammarAccess.getAttributeAccess().getDefaultValueLiteralAssignment_5_1(), "rule__Attribute__DefaultValueLiteralAssignment_5_1");
					put(grammarAccess.getAttributeAccess().getDocuAssignment_6(), "rule__Attribute__DocuAssignment_6");
					put(grammarAccess.getStandardOperationAccess().getNameAssignment_1(), "rule__StandardOperation__NameAssignment_1");
					put(grammarAccess.getStandardOperationAccess().getArgumentsAssignment_3_0(), "rule__StandardOperation__ArgumentsAssignment_3_0");
					put(grammarAccess.getStandardOperationAccess().getArgumentsAssignment_3_1_1(), "rule__StandardOperation__ArgumentsAssignment_3_1_1");
					put(grammarAccess.getStandardOperationAccess().getReturntypeAssignment_5_1_1(), "rule__StandardOperation__ReturntypeAssignment_5_1_1");
					put(grammarAccess.getStandardOperationAccess().getDocuAssignment_6(), "rule__StandardOperation__DocuAssignment_6");
					put(grammarAccess.getStandardOperationAccess().getDetailCodeAssignment_7(), "rule__StandardOperation__DetailCodeAssignment_7");
					put(grammarAccess.getPortOperationAccess().getNameAssignment_1(), "rule__PortOperation__NameAssignment_1");
					put(grammarAccess.getPortOperationAccess().getArgumentsAssignment_3_0(), "rule__PortOperation__ArgumentsAssignment_3_0");
					put(grammarAccess.getPortOperationAccess().getArgumentsAssignment_3_1_1(), "rule__PortOperation__ArgumentsAssignment_3_1_1");
					put(grammarAccess.getPortOperationAccess().getReturntypeAssignment_5_0_1_1(), "rule__PortOperation__ReturntypeAssignment_5_0_1_1");
					put(grammarAccess.getPortOperationAccess().getSendsMsgAssignment_5_1_1(), "rule__PortOperation__SendsMsgAssignment_5_1_1");
					put(grammarAccess.getPortOperationAccess().getDocuAssignment_6(), "rule__PortOperation__DocuAssignment_6");
					put(grammarAccess.getPortOperationAccess().getDetailCodeAssignment_7(), "rule__PortOperation__DetailCodeAssignment_7");
					put(grammarAccess.getProtocolClassAccess().getNameAssignment_1(), "rule__ProtocolClass__NameAssignment_1");
					put(grammarAccess.getProtocolClassAccess().getDocuAssignment_2(), "rule__ProtocolClass__DocuAssignment_2");
					put(grammarAccess.getProtocolClassAccess().getBaseAssignment_3_1(), "rule__ProtocolClass__BaseAssignment_3_1");
					put(grammarAccess.getProtocolClassAccess().getUserCode1Assignment_5_1(), "rule__ProtocolClass__UserCode1Assignment_5_1");
					put(grammarAccess.getProtocolClassAccess().getUserCode2Assignment_6_1(), "rule__ProtocolClass__UserCode2Assignment_6_1");
					put(grammarAccess.getProtocolClassAccess().getUserCode3Assignment_7_1(), "rule__ProtocolClass__UserCode3Assignment_7_1");
					put(grammarAccess.getProtocolClassAccess().getIncomingMessagesAssignment_8_2(), "rule__ProtocolClass__IncomingMessagesAssignment_8_2");
					put(grammarAccess.getProtocolClassAccess().getOutgoingMessagesAssignment_9_2(), "rule__ProtocolClass__OutgoingMessagesAssignment_9_2");
					put(grammarAccess.getProtocolClassAccess().getRegularAssignment_10_2(), "rule__ProtocolClass__RegularAssignment_10_2");
					put(grammarAccess.getProtocolClassAccess().getConjugateAssignment_11_2(), "rule__ProtocolClass__ConjugateAssignment_11_2");
					put(grammarAccess.getProtocolClassAccess().getSemanticsAssignment_12(), "rule__ProtocolClass__SemanticsAssignment_12");
					put(grammarAccess.getMessageAccess().getPrivAssignment_0(), "rule__Message__PrivAssignment_0");
					put(grammarAccess.getMessageAccess().getNameAssignment_2(), "rule__Message__NameAssignment_2");
					put(grammarAccess.getMessageAccess().getDataAssignment_4(), "rule__Message__DataAssignment_4");
					put(grammarAccess.getMessageAccess().getDocuAssignment_6(), "rule__Message__DocuAssignment_6");
					put(grammarAccess.getPortClassAccess().getUserCodeAssignment_1_1(), "rule__PortClass__UserCodeAssignment_1_1");
					put(grammarAccess.getPortClassAccess().getAttributesAssignment_2_0(), "rule__PortClass__AttributesAssignment_2_0");
					put(grammarAccess.getPortClassAccess().getOperationsAssignment_2_1(), "rule__PortClass__OperationsAssignment_2_1");
					put(grammarAccess.getPortClassAccess().getMsgHandlersAssignment_2_2(), "rule__PortClass__MsgHandlersAssignment_2_2");
					put(grammarAccess.getMessageHandlerAccess().getMsgAssignment_1(), "rule__MessageHandler__MsgAssignment_1");
					put(grammarAccess.getMessageHandlerAccess().getDetailCodeAssignment_2(), "rule__MessageHandler__DetailCodeAssignment_2");
					put(grammarAccess.getProtocolSemanticsAccess().getRulesAssignment_3(), "rule__ProtocolSemantics__RulesAssignment_3");
					put(grammarAccess.getSemanticsRuleAccess().getMsgAssignment_0(), "rule__SemanticsRule__MsgAssignment_0");
					put(grammarAccess.getSemanticsRuleAccess().getFollowUpsAssignment_1_1_0(), "rule__SemanticsRule__FollowUpsAssignment_1_1_0");
					put(grammarAccess.getSemanticsRuleAccess().getFollowUpsAssignment_1_1_1_1(), "rule__SemanticsRule__FollowUpsAssignment_1_1_1_1");
					put(grammarAccess.getSemanticsRuleAccess().getFollowUpsAssignment_1_1_1_2_1(), "rule__SemanticsRule__FollowUpsAssignment_1_1_1_2_1");
					put(grammarAccess.getActorClassAccess().getAbstractAssignment_0(), "rule__ActorClass__AbstractAssignment_0");
					put(grammarAccess.getActorClassAccess().getNameAssignment_2(), "rule__ActorClass__NameAssignment_2");
					put(grammarAccess.getActorClassAccess().getDocuAssignment_3(), "rule__ActorClass__DocuAssignment_3");
					put(grammarAccess.getActorClassAccess().getBaseAssignment_4_1(), "rule__ActorClass__BaseAssignment_4_1");
					put(grammarAccess.getActorClassAccess().getIfPortsAssignment_6_2(), "rule__ActorClass__IfPortsAssignment_6_2");
					put(grammarAccess.getActorClassAccess().getIfSPPsAssignment_6_3(), "rule__ActorClass__IfSPPsAssignment_6_3");
					put(grammarAccess.getActorClassAccess().getStructureDocuAssignment_7_1(), "rule__ActorClass__StructureDocuAssignment_7_1");
					put(grammarAccess.getActorClassAccess().getUserCode1Assignment_7_3_1(), "rule__ActorClass__UserCode1Assignment_7_3_1");
					put(grammarAccess.getActorClassAccess().getUserCode2Assignment_7_4_1(), "rule__ActorClass__UserCode2Assignment_7_4_1");
					put(grammarAccess.getActorClassAccess().getUserCode3Assignment_7_5_1(), "rule__ActorClass__UserCode3Assignment_7_5_1");
					put(grammarAccess.getActorClassAccess().getIntPortsAssignment_7_6_0(), "rule__ActorClass__IntPortsAssignment_7_6_0");
					put(grammarAccess.getActorClassAccess().getExtPortsAssignment_7_6_1(), "rule__ActorClass__ExtPortsAssignment_7_6_1");
					put(grammarAccess.getActorClassAccess().getServiceImplementationsAssignment_7_7(), "rule__ActorClass__ServiceImplementationsAssignment_7_7");
					put(grammarAccess.getActorClassAccess().getStrSAPsAssignment_7_8(), "rule__ActorClass__StrSAPsAssignment_7_8");
					put(grammarAccess.getActorClassAccess().getAttributesAssignment_7_9(), "rule__ActorClass__AttributesAssignment_7_9");
					put(grammarAccess.getActorClassAccess().getActorRefsAssignment_7_10(), "rule__ActorClass__ActorRefsAssignment_7_10");
					put(grammarAccess.getActorClassAccess().getBindingsAssignment_7_11(), "rule__ActorClass__BindingsAssignment_7_11");
					put(grammarAccess.getActorClassAccess().getConnectionsAssignment_7_12(), "rule__ActorClass__ConnectionsAssignment_7_12");
					put(grammarAccess.getActorClassAccess().getBehaviorDocuAssignment_8_1(), "rule__ActorClass__BehaviorDocuAssignment_8_1");
					put(grammarAccess.getActorClassAccess().getAnnotationsAssignment_8_3(), "rule__ActorClass__AnnotationsAssignment_8_3");
					put(grammarAccess.getActorClassAccess().getOperationsAssignment_8_4(), "rule__ActorClass__OperationsAssignment_8_4");
					put(grammarAccess.getActorClassAccess().getStateMachineAssignment_8_5(), "rule__ActorClass__StateMachineAssignment_8_5");
					put(grammarAccess.getPortAccess().getConjugatedAssignment_0(), "rule__Port__ConjugatedAssignment_0");
					put(grammarAccess.getPortAccess().getNameAssignment_2(), "rule__Port__NameAssignment_2");
					put(grammarAccess.getPortAccess().getMultiplicityAssignment_3(), "rule__Port__MultiplicityAssignment_3");
					put(grammarAccess.getPortAccess().getProtocolAssignment_5(), "rule__Port__ProtocolAssignment_5");
					put(grammarAccess.getPortAccess().getDocuAssignment_6(), "rule__Port__DocuAssignment_6");
					put(grammarAccess.getExternalPortAccess().getIfportAssignment_2(), "rule__ExternalPort__IfportAssignment_2");
					put(grammarAccess.getSAPRefAccess().getNameAssignment_1(), "rule__SAPRef__NameAssignment_1");
					put(grammarAccess.getSAPRefAccess().getProtocolAssignment_3(), "rule__SAPRef__ProtocolAssignment_3");
					put(grammarAccess.getSPPRefAccess().getNameAssignment_1(), "rule__SPPRef__NameAssignment_1");
					put(grammarAccess.getSPPRefAccess().getProtocolAssignment_3(), "rule__SPPRef__ProtocolAssignment_3");
					put(grammarAccess.getServiceImplementationAccess().getSppAssignment_2(), "rule__ServiceImplementation__SppAssignment_2");
					put(grammarAccess.getLogicalSystemAccess().getNameAssignment_1(), "rule__LogicalSystem__NameAssignment_1");
					put(grammarAccess.getLogicalSystemAccess().getDocuAssignment_2(), "rule__LogicalSystem__DocuAssignment_2");
					put(grammarAccess.getLogicalSystemAccess().getSubSystemsAssignment_4(), "rule__LogicalSystem__SubSystemsAssignment_4");
					put(grammarAccess.getLogicalSystemAccess().getBindingsAssignment_5(), "rule__LogicalSystem__BindingsAssignment_5");
					put(grammarAccess.getLogicalSystemAccess().getConnectionsAssignment_6(), "rule__LogicalSystem__ConnectionsAssignment_6");
					put(grammarAccess.getSubSystemRefAccess().getNameAssignment_1(), "rule__SubSystemRef__NameAssignment_1");
					put(grammarAccess.getSubSystemRefAccess().getTypeAssignment_3(), "rule__SubSystemRef__TypeAssignment_3");
					put(grammarAccess.getSubSystemRefAccess().getDocuAssignment_4(), "rule__SubSystemRef__DocuAssignment_4");
					put(grammarAccess.getSubSystemClassAccess().getNameAssignment_1(), "rule__SubSystemClass__NameAssignment_1");
					put(grammarAccess.getSubSystemClassAccess().getDocuAssignment_2(), "rule__SubSystemClass__DocuAssignment_2");
					put(grammarAccess.getSubSystemClassAccess().getUserCode1Assignment_4_1(), "rule__SubSystemClass__UserCode1Assignment_4_1");
					put(grammarAccess.getSubSystemClassAccess().getUserCode2Assignment_5_1(), "rule__SubSystemClass__UserCode2Assignment_5_1");
					put(grammarAccess.getSubSystemClassAccess().getUserCode3Assignment_6_1(), "rule__SubSystemClass__UserCode3Assignment_6_1");
					put(grammarAccess.getSubSystemClassAccess().getRelayPortsAssignment_7(), "rule__SubSystemClass__RelayPortsAssignment_7");
					put(grammarAccess.getSubSystemClassAccess().getIfSPPsAssignment_8(), "rule__SubSystemClass__IfSPPsAssignment_8");
					put(grammarAccess.getSubSystemClassAccess().getActorRefsAssignment_9(), "rule__SubSystemClass__ActorRefsAssignment_9");
					put(grammarAccess.getSubSystemClassAccess().getBindingsAssignment_10(), "rule__SubSystemClass__BindingsAssignment_10");
					put(grammarAccess.getSubSystemClassAccess().getConnectionsAssignment_11(), "rule__SubSystemClass__ConnectionsAssignment_11");
					put(grammarAccess.getSubSystemClassAccess().getThreadsAssignment_12(), "rule__SubSystemClass__ThreadsAssignment_12");
					put(grammarAccess.getLogicalThreadAccess().getNameAssignment_1(), "rule__LogicalThread__NameAssignment_1");
					put(grammarAccess.getLogicalThreadAccess().getPrioAssignment_4(), "rule__LogicalThread__PrioAssignment_4");
					put(grammarAccess.getLogicalThreadAccess().getInstancesAssignment_6(), "rule__LogicalThread__InstancesAssignment_6");
					put(grammarAccess.getLogicalThreadAccess().getInstancesAssignment_7_1(), "rule__LogicalThread__InstancesAssignment_7_1");
					put(grammarAccess.getActorInstancePathAccess().getSegmentsAssignment_0(), "rule__ActorInstancePath__SegmentsAssignment_0");
					put(grammarAccess.getActorInstancePathAccess().getSegmentsAssignment_1_1(), "rule__ActorInstancePath__SegmentsAssignment_1_1");
					put(grammarAccess.getBindingAccess().getEndpoint1Assignment_1(), "rule__Binding__Endpoint1Assignment_1");
					put(grammarAccess.getBindingAccess().getEndpoint2Assignment_3(), "rule__Binding__Endpoint2Assignment_3");
					put(grammarAccess.getBindingEndPointAccess().getActorRefAssignment_0_0(), "rule__BindingEndPoint__ActorRefAssignment_0_0");
					put(grammarAccess.getBindingEndPointAccess().getPortAssignment_1(), "rule__BindingEndPoint__PortAssignment_1");
					put(grammarAccess.getLayerConnectionAccess().getFromAssignment_1(), "rule__LayerConnection__FromAssignment_1");
					put(grammarAccess.getLayerConnectionAccess().getToAssignment_3(), "rule__LayerConnection__ToAssignment_3");
					put(grammarAccess.getRefSAPointAccess().getRefAssignment_1(), "rule__RefSAPoint__RefAssignment_1");
					put(grammarAccess.getRelaySAPointAccess().getRelayAssignment_1(), "rule__RelaySAPoint__RelayAssignment_1");
					put(grammarAccess.getSPPointAccess().getRefAssignment_0(), "rule__SPPoint__RefAssignment_0");
					put(grammarAccess.getSPPointAccess().getServiceAssignment_2(), "rule__SPPoint__ServiceAssignment_2");
					put(grammarAccess.getActorRefAccess().getNameAssignment_1(), "rule__ActorRef__NameAssignment_1");
					put(grammarAccess.getActorRefAccess().getTypeAssignment_3(), "rule__ActorRef__TypeAssignment_3");
					put(grammarAccess.getActorRefAccess().getDocuAssignment_4(), "rule__ActorRef__DocuAssignment_4");
					put(grammarAccess.getPlainStateGraphAccess().getStatesAssignment_2_0(), "rule__PlainStateGraph__StatesAssignment_2_0");
					put(grammarAccess.getPlainStateGraphAccess().getTrPointsAssignment_2_1(), "rule__PlainStateGraph__TrPointsAssignment_2_1");
					put(grammarAccess.getPlainStateGraphAccess().getChPointsAssignment_2_2(), "rule__PlainStateGraph__ChPointsAssignment_2_2");
					put(grammarAccess.getPlainStateGraphAccess().getTransitionsAssignment_2_3(), "rule__PlainStateGraph__TransitionsAssignment_2_3");
					put(grammarAccess.getStateMachineAccess().getDataDrivenAssignment_1(), "rule__StateMachine__DataDrivenAssignment_1");
					put(grammarAccess.getStateMachineAccess().getStatesAssignment_4_0(), "rule__StateMachine__StatesAssignment_4_0");
					put(grammarAccess.getStateMachineAccess().getTrPointsAssignment_4_1(), "rule__StateMachine__TrPointsAssignment_4_1");
					put(grammarAccess.getStateMachineAccess().getChPointsAssignment_4_2(), "rule__StateMachine__ChPointsAssignment_4_2");
					put(grammarAccess.getStateMachineAccess().getTransitionsAssignment_4_3(), "rule__StateMachine__TransitionsAssignment_4_3");
					put(grammarAccess.getBaseStateAccess().getNameAssignment_1(), "rule__BaseState__NameAssignment_1");
					put(grammarAccess.getBaseStateAccess().getDocuAssignment_2(), "rule__BaseState__DocuAssignment_2");
					put(grammarAccess.getBaseStateAccess().getEntryCodeAssignment_3_1_1(), "rule__BaseState__EntryCodeAssignment_3_1_1");
					put(grammarAccess.getBaseStateAccess().getExitCodeAssignment_3_2_1(), "rule__BaseState__ExitCodeAssignment_3_2_1");
					put(grammarAccess.getBaseStateAccess().getDoCodeAssignment_3_3_1(), "rule__BaseState__DoCodeAssignment_3_3_1");
					put(grammarAccess.getBaseStateAccess().getSubgraphAssignment_3_4_1(), "rule__BaseState__SubgraphAssignment_3_4_1");
					put(grammarAccess.getRefinedStateAccess().getBaseAssignment_1(), "rule__RefinedState__BaseAssignment_1");
					put(grammarAccess.getRefinedStateAccess().getDocuAssignment_2(), "rule__RefinedState__DocuAssignment_2");
					put(grammarAccess.getRefinedStateAccess().getEntryCodeAssignment_4_1(), "rule__RefinedState__EntryCodeAssignment_4_1");
					put(grammarAccess.getRefinedStateAccess().getExitCodeAssignment_5_1(), "rule__RefinedState__ExitCodeAssignment_5_1");
					put(grammarAccess.getRefinedStateAccess().getDoCodeAssignment_6_1(), "rule__RefinedState__DoCodeAssignment_6_1");
					put(grammarAccess.getRefinedStateAccess().getSubgraphAssignment_7_1(), "rule__RefinedState__SubgraphAssignment_7_1");
					put(grammarAccess.getDetailCodeAccess().getCommandsAssignment_1(), "rule__DetailCode__CommandsAssignment_1");
					put(grammarAccess.getTransitionPointAccess().getHandlerAssignment_0(), "rule__TransitionPoint__HandlerAssignment_0");
					put(grammarAccess.getTransitionPointAccess().getNameAssignment_2(), "rule__TransitionPoint__NameAssignment_2");
					put(grammarAccess.getEntryPointAccess().getNameAssignment_1(), "rule__EntryPoint__NameAssignment_1");
					put(grammarAccess.getExitPointAccess().getNameAssignment_1(), "rule__ExitPoint__NameAssignment_1");
					put(grammarAccess.getChoicePointAccess().getNameAssignment_1(), "rule__ChoicePoint__NameAssignment_1");
					put(grammarAccess.getChoicePointAccess().getDocuAssignment_2(), "rule__ChoicePoint__DocuAssignment_2");
					put(grammarAccess.getInitialTransitionAccess().getNameAssignment_1(), "rule__InitialTransition__NameAssignment_1");
					put(grammarAccess.getInitialTransitionAccess().getToAssignment_5(), "rule__InitialTransition__ToAssignment_5");
					put(grammarAccess.getInitialTransitionAccess().getDocuAssignment_6(), "rule__InitialTransition__DocuAssignment_6");
					put(grammarAccess.getInitialTransitionAccess().getActionAssignment_8_1(), "rule__InitialTransition__ActionAssignment_8_1");
					put(grammarAccess.getContinuationTransitionAccess().getNameAssignment_1(), "rule__ContinuationTransition__NameAssignment_1");
					put(grammarAccess.getContinuationTransitionAccess().getFromAssignment_3(), "rule__ContinuationTransition__FromAssignment_3");
					put(grammarAccess.getContinuationTransitionAccess().getToAssignment_5(), "rule__ContinuationTransition__ToAssignment_5");
					put(grammarAccess.getContinuationTransitionAccess().getDocuAssignment_6(), "rule__ContinuationTransition__DocuAssignment_6");
					put(grammarAccess.getContinuationTransitionAccess().getActionAssignment_7_1_1(), "rule__ContinuationTransition__ActionAssignment_7_1_1");
					put(grammarAccess.getTriggeredTransitionAccess().getNameAssignment_1(), "rule__TriggeredTransition__NameAssignment_1");
					put(grammarAccess.getTriggeredTransitionAccess().getFromAssignment_3(), "rule__TriggeredTransition__FromAssignment_3");
					put(grammarAccess.getTriggeredTransitionAccess().getToAssignment_5(), "rule__TriggeredTransition__ToAssignment_5");
					put(grammarAccess.getTriggeredTransitionAccess().getDocuAssignment_6(), "rule__TriggeredTransition__DocuAssignment_6");
					put(grammarAccess.getTriggeredTransitionAccess().getTriggersAssignment_10(), "rule__TriggeredTransition__TriggersAssignment_10");
					put(grammarAccess.getTriggeredTransitionAccess().getTriggersAssignment_11_1(), "rule__TriggeredTransition__TriggersAssignment_11_1");
					put(grammarAccess.getTriggeredTransitionAccess().getActionAssignment_13_1(), "rule__TriggeredTransition__ActionAssignment_13_1");
					put(grammarAccess.getGuardedTransitionAccess().getNameAssignment_1(), "rule__GuardedTransition__NameAssignment_1");
					put(grammarAccess.getGuardedTransitionAccess().getFromAssignment_3(), "rule__GuardedTransition__FromAssignment_3");
					put(grammarAccess.getGuardedTransitionAccess().getToAssignment_5(), "rule__GuardedTransition__ToAssignment_5");
					put(grammarAccess.getGuardedTransitionAccess().getDocuAssignment_6(), "rule__GuardedTransition__DocuAssignment_6");
					put(grammarAccess.getGuardedTransitionAccess().getGuardAssignment_9(), "rule__GuardedTransition__GuardAssignment_9");
					put(grammarAccess.getGuardedTransitionAccess().getActionAssignment_10_1(), "rule__GuardedTransition__ActionAssignment_10_1");
					put(grammarAccess.getCPBranchTransitionAccess().getNameAssignment_1(), "rule__CPBranchTransition__NameAssignment_1");
					put(grammarAccess.getCPBranchTransitionAccess().getFromAssignment_3(), "rule__CPBranchTransition__FromAssignment_3");
					put(grammarAccess.getCPBranchTransitionAccess().getToAssignment_5(), "rule__CPBranchTransition__ToAssignment_5");
					put(grammarAccess.getCPBranchTransitionAccess().getDocuAssignment_6(), "rule__CPBranchTransition__DocuAssignment_6");
					put(grammarAccess.getCPBranchTransitionAccess().getConditionAssignment_9(), "rule__CPBranchTransition__ConditionAssignment_9");
					put(grammarAccess.getCPBranchTransitionAccess().getActionAssignment_10_1(), "rule__CPBranchTransition__ActionAssignment_10_1");
					put(grammarAccess.getStateTerminalAccess().getStateAssignment(), "rule__StateTerminal__StateAssignment");
					put(grammarAccess.getTrPointTerminalAccess().getTrPointAssignment_1(), "rule__TrPointTerminal__TrPointAssignment_1");
					put(grammarAccess.getSubStateTrPointTerminalAccess().getTrPointAssignment_0(), "rule__SubStateTrPointTerminal__TrPointAssignment_0");
					put(grammarAccess.getSubStateTrPointTerminalAccess().getStateAssignment_2(), "rule__SubStateTrPointTerminal__StateAssignment_2");
					put(grammarAccess.getChoicepointTerminalAccess().getCpAssignment_1(), "rule__ChoicepointTerminal__CpAssignment_1");
					put(grammarAccess.getTriggerAccess().getMsgFromIfPairsAssignment_1(), "rule__Trigger__MsgFromIfPairsAssignment_1");
					put(grammarAccess.getTriggerAccess().getMsgFromIfPairsAssignment_2_1(), "rule__Trigger__MsgFromIfPairsAssignment_2_1");
					put(grammarAccess.getTriggerAccess().getGuardAssignment_3(), "rule__Trigger__GuardAssignment_3");
					put(grammarAccess.getMessageFromIfAccess().getMessageAssignment_0(), "rule__MessageFromIf__MessageAssignment_0");
					put(grammarAccess.getMessageFromIfAccess().getFromAssignment_2(), "rule__MessageFromIf__FromAssignment_2");
					put(grammarAccess.getGuardAccess().getGuardAssignment_1(), "rule__Guard__GuardAssignment_1");
					put(grammarAccess.getDocumentationAccess().getTextAssignment_1(), "rule__Documentation__TextAssignment_1");
					put(grammarAccess.getAnnotationAccess().getNameAssignment_1(), "rule__Annotation__NameAssignment_1");
					put(grammarAccess.getAnnotationAccess().getAttributesAssignment_2_1(), "rule__Annotation__AttributesAssignment_2_1");
					put(grammarAccess.getAnnotationAccess().getAttributesAssignment_2_2_1(), "rule__Annotation__AttributesAssignment_2_2_1");
					put(grammarAccess.getKeyValueAccess().getKeyAssignment_0(), "rule__KeyValue__KeyAssignment_0");
					put(grammarAccess.getKeyValueAccess().getValueAssignment_2(), "rule__KeyValue__ValueAssignment_2");
					put(grammarAccess.getImportAccess().getImportedNamespaceAssignment_1_0_0(), "rule__Import__ImportedNamespaceAssignment_1_0_0");
					put(grammarAccess.getImportAccess().getImportURIAssignment_2(), "rule__Import__ImportURIAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.eclipse.etrice.core.ui.contentassist.antlr.internal.InternalRoomParser typedParser = (org.eclipse.etrice.core.ui.contentassist.antlr.internal.InternalRoomParser) parser;
			typedParser.entryRuleRoomModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public RoomGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RoomGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
