/**
 * @author generated by eTrice
 *
 * Source File of ActorClass ReceiverManual
 * 
 */

#include "ReceiverManual.h"

#include "etLogger.h"

#include "etMSCLogger.h"


void ReceiverManual_init(ReceiverManual* self){
	ET_MSC_LOGGER_SYNC_ENTRY("ReceiverManual", "init")
	CommunicationProtocolPort_outMessage1(&self->constData->dataIn);
	CommunicationProtocolPort_outMessage2(&self->constData->dataIn);
	CommunicationProtocolPort_outMessage123456789(&self->constData->dataIn);
	ET_MSC_LOGGER_SYNC_EXIT
}


void ReceiverManual_ReceiveMessage(void* self, etInt16 localId, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("ReceiverManual", "ReceiveMessage")
	ET_MSC_LOGGER_SYNC_EXIT
}

