/**
 * @author generated by eTrice
 *
 * Header File of ActorClass ReceiverManual
 * 
 */

#ifndef _RECEIVERMANUAL_H_
#define _RECEIVERMANUAL_H_

#include "etDatatypes.h"


#include "CommunicationProtocol.h"


typedef struct ReceiverManual ReceiverManual;

/* const part of ActorClass (ROM) */
typedef struct ReceiverManual_const {
	const ReceiverManual* actor;
	/* Ports */
	const CommunicationProtocolPort dataIn;
	
} ReceiverManual_const;

/* variable part of ActorClass (RAM) */
struct ReceiverManual {
	const ReceiverManual_const* constData;
};

void ReceiverManual_init(ReceiverManual* self);

void ReceiverManual_ReceiveMessage(void* self, etInt16 localId, const etMessage* msg);




#endif /* _RECEIVERMANUAL_H_ */

