/**
 * @author generated by eTrice
 *
 * Source File of ActorClass ReceiverManual
 * 
 */

#include "ReceiverManual.h"


void ReceiverManual_ReceiveMessage(void* self, etInt16 localId, const etMessage*){
	etLogger_logInfoF("ReceiverManual_ReceiveMessage");
}

