/**
 * @author generated by eTrice
 *
 * Source File of ActorClass SenderManual
 * 
 */

#include "SenderManual.h"


void SenderManual_ReceiveMessage(void* self, etInt16 localId, const etMessage*){
	etLogger_logInfoF("SenderManual_ReceiveMessage");
}

