/**
 * @author generated by eTrice
 *
 * Header File of ActorClass SenderManual
 * 
 */

#ifndef _SENDERMANUAL_H_
#define _SENDERMANUAL_H_

#include "etDatatypes.h"

#include "DataClass1.h"

#include "CommunicationProtocol.h"


typedef struct SenderManual SenderManual;

/* const part of ActorClass (ROM) */
typedef struct SenderManual_const {
	const SenderManual* actor;
	/* Ports */
	const CommunicationProtocolConjPort dataOut;
	
} SenderManual_const;

/* variable part of ActorClass (RAM) */
struct SenderManual {
	const SenderManual_const* constData;
};

void SenderManual_ReceiveMessage(void* self, etInt16 localId, const etMessage*);




#endif /* _SENDERMANUAL_H_ */

