/**
 * @author generated by eTrice
 *
 * Header File of SubSystemClass SubSys
 * 
 */

#ifndef _SUBSYS_H_
#define _SUBSYS_H_


/* lifecycle functions
 * init -> start -> run (loop) -> stop -> destroy
 */

void SubSys_init(void); // lifecycle init
void SubSys_start(void); // lifecycle start

void SubSys_run(void);

void SubSys_stop(void); // lifecycle stop
void SubSys_destroy(void); // lifecycle destroy


#endif /* _SUBSYS_H_ */


