/**
 * @author generated by eTrice
 *
 * Dispatcher File of SubSystemClass SubSys
 * - one generated dispatcher for each MessageService (Thread)
 */

#include "etMessageReceiver.h"
#include "etLogger.h"

void MsgService_Thread1_ReceiveMessage(const etMessage* msg){
	switch(msg->address){
	
		/* interface items of /SubSys/Receiver */
		case 102:
			etPort_receive(&/SubSys/Receiver_const.dataIn, msg);
			break;
		/* interface items of /SubSys/Sender */
		case 104:
			etPort_receive(&/SubSys/Sender_const.dataOut, msg);
			break;

		default:
			etLogger_logErrorF("MessageService_Thread1_ReceiveMessage: address %d does not exist ", msg->address);
			break;
	}
}
