/**
 * @author generated by eTrice
 *
 * this class contains the main function running component SubSys
 * it instantiates SubSys and starts and ends the lifecycle
 */


#include "SubSys.h"

#include "etLogger.h"
#include "etMSCLogger.h"


/**
 * main function
 * creates component and starts and stops the lifecycle
 */

int main(void) {

	etLogger_logInfo("***   T H E   B E G I N   ***");
	ET_MSC_LOGGER_OPEN("main");

	/* startup sequence  of lifecycle */
	SubSys_init(); 		/* lifecycle init */
	SubSys_start(); 	/* lifecycle start */

	/* run Scheduler */
	SubSys_run();

	/* shutdown sequence of lifecycle */
	SubSys_stop(); 		/* lifecycle stop */
	SubSys_destroy(); 	/* lifecycle destroy */

	ET_MSC_LOGGER_CLOSE
	etLogger_logInfo("***   T H E   E N D   ***");

	return 0;
}

