/**
 * @author generated by eTrice
 *
 * Source File of SubSystemClass SubSys
 * 
 */

#include "SubSys.h"

#include "etLogger.h"

/* data for SubSysten SubSys */
typedef struct SubSys {
	char *name;
} SubSys;

static SubSys SubSysInst = {"SubSys"};

void SubSys_init(void){
	etLogger_logInfoF("%s_init", SubSysInst.name);
}

void SubSys_start(void){
	etLogger_logInfoF("%s_start", SubSysInst.name);
}

void SubSys_run(void){
	int32 i;
	for (i=0; i<100; i++){
		etLogger_logInfoF("%s Scheduler tick %d", SubSysInst.name, i);
	}
}

void SubSys_stop(void){
	etLogger_logInfoF("%s_stop", SubSysInst.name);
}

void SubSys_destroy(void){
	etLogger_logInfoF("%s_destroy", SubSysInst.name);
}


