/**
 * @author generated by eTrice
 *
 * this class contains the main function running component SendingData_SubSystem
 * it instantiates SendingData_SubSystem and starts and ends the lifecycle
 */

package SendingData;

import org.eclipse.etrice.runtime.java.modelbase.SubSystemRunnerBase;

class SendingData_SubSystemRunner extends SubSystemRunnerBase {

	static SendingData_SubSystem main_component = new SendingData_SubSystem(null, "SendingData_SubSystem");

	/**
     * main function
     * creates component and starts and stops the lifecycle
     */
	public static void main(String[] args) {

		System.out.println("***   T H E   B E G I N   ***");
		
		main_component.init(); // lifecycle init
		main_component.start(); // lifecycle start

		// application runs until quit 
		waitForQuit();
		
		// end the lifecycle
		main_component.stop(); // lifecycle stop
		main_component.destroy(); // lifecycle destroy

		System.out.println("***   T H E   E N D   ***");
	}
};
