/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.etrice.generator.etricegen.validation;

import org.eclipse.etrice.core.room.InterfaceItem;
import org.eclipse.etrice.core.room.Message;
import org.eclipse.etrice.core.room.TriggeredTransition;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.eclipse.etrice.generator.etricegen.ActiveTrigger}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActiveTriggerValidator {
	boolean validate();

	boolean validateMsg(Message value);
	boolean validateIfitem(InterfaceItem value);
	boolean validateTrigger(String value);
	boolean validateTransitions(EList<TriggeredTransition> value);
}
