/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.etrice.generator.etricegen.validation;

import org.eclipse.etrice.core.room.LayerConnection;
import org.eclipse.etrice.generator.etricegen.ActorInstance;
import org.eclipse.etrice.generator.etricegen.SPPInstance;

/**
 * A sample validator interface for {@link org.eclipse.etrice.generator.etricegen.ConnectionInstance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConnectionInstanceValidator {
	boolean validate();

	boolean validateFromAI(ActorInstance value);
	boolean validateFromSPP(SPPInstance value);
	boolean validateToSPP(SPPInstance value);
	boolean validateConnection(LayerConnection value);
}
