/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.etrice.generator.etricegen.validation;


import org.eclipse.emf.common.util.EList;
import org.eclipse.etrice.generator.etricegen.InterfaceItemInstance;

/**
 * A sample validator interface for {@link org.eclipse.etrice.generator.etricegen.InterfaceItemInstance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InterfaceItemInstanceValidator {
	boolean validate();

	boolean validatePeers(EList<InterfaceItemInstance> value);
}
