/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.etrice.generator.etricegen.validation;


import org.eclipse.etrice.core.room.SPPRef;
import org.eclipse.etrice.generator.etricegen.ConnectionInstance;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.eclipse.etrice.generator.etricegen.SPPInstance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SPPInstanceValidator {
	boolean validate();

	boolean validateSpp(SPPRef value);
	boolean validateIncoming(EList<ConnectionInstance> value);
	boolean validateOutgoing(ConnectionInstance value);
}
